package com.charity.charity.services;


import java.util.ArrayList;
import java.util.List;

public class ArrayWithFiltersOptions {


    public static List<String> optionsCountry() {
        List<String> optionsCountry = new ArrayList<>();
        optionsCountry.add("Abkhazia");
        optionsCountry.add("Australia");
        optionsCountry.add("Austria");
        optionsCountry.add("Azerbaijan");
        optionsCountry.add("Albania");
        optionsCountry.add("Algeria");
        optionsCountry.add("Am.VirginIslands");
        optionsCountry.add("AmericanSamoa");
        optionsCountry.add("Angola");
        optionsCountry.add("Andorra");
        optionsCountry.add("AntiguaandBarbuda");
        optionsCountry.add("Argentina");
        optionsCountry.add("Armenia");
        optionsCountry.add("Aruba");
        optionsCountry.add("Afghanistan");
        optionsCountry.add("Bahamas");
        optionsCountry.add("Bangladesh");
        optionsCountry.add("Barbados");
        optionsCountry.add("Bahrain");
        optionsCountry.add("Belize");
        optionsCountry.add("Belarus");
        optionsCountry.add("Belgium");
        optionsCountry.add("Benin");
        optionsCountry.add("Bermuda");
        optionsCountry.add("Bulgaria");
        optionsCountry.add("Bolivia");
        optionsCountry.add("Bonaire");
        optionsCountry.add("BosniaandHerzegovina");
        optionsCountry.add("Botswana");
        optionsCountry.add("Brazil");
        optionsCountry.add("Br.VirginIslands");
        optionsCountry.add("Brunei");
        optionsCountry.add("BurkinaFaso");
        optionsCountry.add("Burundi");
        optionsCountry.add("Butane");
        optionsCountry.add("Vanuatu");
        optionsCountry.add("Vatican");
        optionsCountry.add("GreatBritain");
        optionsCountry.add("Hungary");
        optionsCountry.add("Venezuela");
        optionsCountry.add("EastTimor");
        optionsCountry.add("Vietnam");
        optionsCountry.add("Gabon");
        optionsCountry.add("Haiti");
        optionsCountry.add("Guyana");
        optionsCountry.add("Gambia");
        optionsCountry.add("Ghana");
        optionsCountry.add("Guatemala");
        optionsCountry.add("Guinea");
        optionsCountry.add("Guinea-Bissau");
        optionsCountry.add("Germany");
        optionsCountry.add("Honduras");
        optionsCountry.add("HongKong");
        optionsCountry.add("Grenada");
        optionsCountry.add("Greece");
        optionsCountry.add("Georgia");
        optionsCountry.add("Denmark");
        optionsCountry.add("D.R.Congo");
        optionsCountry.add("Jersey");
        optionsCountry.add("Djibouti");
        optionsCountry.add("Dominica");
        optionsCountry.add("DominicanRepublic");
        optionsCountry.add("Egypt");
        optionsCountry.add("Zambia");
        optionsCountry.add("Zimbabwe");
        optionsCountry.add("Israel");
        optionsCountry.add("India");
        optionsCountry.add("Indonesia");
        optionsCountry.add("Jordan");
        optionsCountry.add("Iraq");
        optionsCountry.add("Iran");
        optionsCountry.add("Ireland");
        optionsCountry.add("Iceland");
        optionsCountry.add("Spain");
        optionsCountry.add("Italy");
        optionsCountry.add("Yemen");
        optionsCountry.add("CapeVerde");
        optionsCountry.add("Kazakhstan");
        optionsCountry.add("Cambodia");
        optionsCountry.add("Cameroon");
        optionsCountry.add("Canada");
        optionsCountry.add("Qatar");
        optionsCountry.add("Kenya");
        optionsCountry.add("Cyprus");
        optionsCountry.add("Kyrgyzstan");
        optionsCountry.add("Kiribati");
        optionsCountry.add("China");
        optionsCountry.add("Colombia");
        optionsCountry.add("coconutislands");
        optionsCountry.add("Comoros");
        optionsCountry.add("Congo");
        optionsCountry.add("NorthKorea");
        optionsCountry.add("Korea");
        optionsCountry.add("CostaRica");
        optionsCountry.add("IvoryCoast");
        optionsCountry.add("Cuba");
        optionsCountry.add("Kuwait");
        optionsCountry.add("Curacao");
        optionsCountry.add("Laos");
        optionsCountry.add("Latvia");
        optionsCountry.add("Lesotho");
        optionsCountry.add("Liberia");
        optionsCountry.add("Lebanon");
        optionsCountry.add("Libya");
        optionsCountry.add("Lithuania");
        optionsCountry.add("Liechtenstein");
        optionsCountry.add("Luxembourg");
        optionsCountry.add("Mauritius");
        optionsCountry.add("Mauritania");
        optionsCountry.add("Madagascar");
        optionsCountry.add("Macedonia");
        optionsCountry.add("Malawi");
        optionsCountry.add("Malaysia");
        optionsCountry.add("Mali");
        optionsCountry.add("Malta");
        optionsCountry.add("Maldives");
        optionsCountry.add("Morocco");
        optionsCountry.add("MarshallIslands");
        optionsCountry.add("Mexico");
        optionsCountry.add("Mozambique");
        optionsCountry.add("Moldova");
        optionsCountry.add("Monaco");
        optionsCountry.add("Mongolia");
        optionsCountry.add("Myanmar");
        optionsCountry.add("Namibia");
        optionsCountry.add("Nauru");
        optionsCountry.add("Nepal");
        optionsCountry.add("Niger");
        optionsCountry.add("Nigeria");
        optionsCountry.add("Netherlands");
        optionsCountry.add("Nicaragua");
        optionsCountry.add("NewZealand");
        optionsCountry.add("Norway");
        optionsCountry.add("UAE");
        optionsCountry.add("Oman");
        optionsCountry.add("CookIslands");
        optionsCountry.add("Pakistan");
        optionsCountry.add("Palau");
        optionsCountry.add("Panama");
        optionsCountry.add("PapuaNewGuinea");
        optionsCountry.add("Paraguay");
        optionsCountry.add("Peru");
        optionsCountry.add("PuertoRico");
        optionsCountry.add("Poland");
        optionsCountry.add("Portugal");
        optionsCountry.add("Russia");
        optionsCountry.add("Rwanda");
        optionsCountry.add("Romania");
        optionsCountry.add("Saba");
        optionsCountry.add("Salvador");
        optionsCountry.add("Samoa");
        optionsCountry.add("SanMarino");
        optionsCountry.add("SaoTomeAndPrincipe");
        optionsCountry.add("SaudiArabia");
        optionsCountry.add("Swaziland");
        optionsCountry.add("Seychelles");
        optionsCountry.add("Senegal");
        optionsCountry.add("SaintVincentandtheGrenadines");
        optionsCountry.add("SaintKittsandNevis");
        optionsCountry.add("SaintLucia");
        optionsCountry.add("SaintMartin");
        optionsCountry.add("Serbia");
        optionsCountry.add("Singapore");
        optionsCountry.add("SintEustatius");
        optionsCountry.add("Syria");
        optionsCountry.add("Slovakia");
        optionsCountry.add("Slovenia");
        optionsCountry.add("USA");
        optionsCountry.add("Solomonislands");
        optionsCountry.add("Somalia");
        optionsCountry.add("Sudan");
        optionsCountry.add("Suriname");
        optionsCountry.add("SierraLeone");
        optionsCountry.add("Tajikistan");
        optionsCountry.add("Thailand");
        optionsCountry.add("Tanzania");
        optionsCountry.add("Togo");
        optionsCountry.add("Tokelau");
        optionsCountry.add("Tonga");
        optionsCountry.add("TrinidadandTobago");
        optionsCountry.add("Tuvalu");
        optionsCountry.add("Tunisia");
        optionsCountry.add("Turkmenistan");
        optionsCountry.add("Turkey");
        optionsCountry.add("Uganda");
        optionsCountry.add("Uzbekistan");
        optionsCountry.add("Ukraine");
        optionsCountry.add("WallisandFutuna");
        optionsCountry.add("Uruguay");
        optionsCountry.add("Faroeislands");
        optionsCountry.add("Fed.StatesofMicronesia");
        optionsCountry.add("Fiji");
        optionsCountry.add("Philippines");
        optionsCountry.add("Finland");
        optionsCountry.add("FalklandIslands");
        optionsCountry.add("France");
        optionsCountry.add("Frenchpolynesia");
        optionsCountry.add("Croatia");
        optionsCountry.add("CAR");
        optionsCountry.add("Chad");
        optionsCountry.add("Montenegro");
        optionsCountry.add("Czech");
        optionsCountry.add("Chile");
        optionsCountry.add("Switzerland");
        optionsCountry.add("Sweden");
        optionsCountry.add("SriLanka");
        optionsCountry.add("Ecuador");
        optionsCountry.add("EquatorialGuinea");
        optionsCountry.add("Eritrea");
        optionsCountry.add("Estonia");
        optionsCountry.add("Ethiopia");
        optionsCountry.add("SouthAfrica");
        optionsCountry.add("SouthSudan");
        optionsCountry.add("Jamaica");
        optionsCountry.add("Japan");



//        optionsCountry.add("Australia");
//        optionsCountry.add("Austria");
//        optionsCountry.add("Azerbaijan");
//        optionsCountry.add("Albania");
//        optionsCountry.add("Algeria");
//        optionsCountry.add("AmericanSamoa");
//        optionsCountry.add("Anguilla");
//        optionsCountry.add("England");
//        optionsCountry.add("Angola");
//        optionsCountry.add("Andorra");
//        optionsCountry.add("AntiguaAndBarbuda");
//        optionsCountry.add("Argentina");
//        optionsCountry.add("Armenia");
//        optionsCountry.add("Aruba");
//        optionsCountry.add("Afghanistan");
//        optionsCountry.add("Bahamas");
//        optionsCountry.add("Bangladesh");


        return optionsCountry;

    }

}
